package com.fs.myerp.mybatis.model;

import java.util.Date;

public class Emp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.id
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.userid
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.pwd
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.name
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.create_date
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.id
     *
     * @return the value of emp.id
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.id
     *
     * @param id the value for emp.id
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.userid
     *
     * @return the value of emp.userid
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.userid
     *
     * @param userid the value for emp.userid
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid == null ? null : userid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.pwd
     *
     * @return the value of emp.pwd
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.pwd
     *
     * @param pwd the value for emp.pwd
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.name
     *
     * @return the value of emp.name
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.name
     *
     * @param name the value for emp.name
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.create_date
     *
     * @return the value of emp.create_date
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.create_date
     *
     * @param createDate the value for emp.create_date
     *
     * @mbg.generated Mon Jul 08 19:57:49 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}